// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },

  // ── Datasource ───────────────────────────────────────────────────────────
  // Prisma 7: the url block here is for the CLI (migrate, studio).
  // For Neon, pass the *direct* (non-pooled) URL so `prisma migrate`
  // can open a long-lived connection — the pooler URL breaks DDL.
  //
  //   DATABASE_URL        → pooled Neon URL  (used by PrismaNeon adapter at runtime)
  //   DIRECT_DATABASE_URL → direct Neon URL  (used by the CLI for migrations)
  datasource: {
    url: env("DATABASE_URL"),
  },
});
